[
    {
        name: 'SAMSUNG A04 NF',
        type: 'lcd',
        price: 15,
        stock: 100,
    },
    {
        name: 'SAMSUNG A04S NF',
        type: 'lcd',
        price: 15,
        stock: 100,
    },
    {
        name: 'SAMSUNG A04E NF',
        type: 'lcd',
        price: 17,
        stock: 100,
    },
    {
        name: 'SAMSUNG A02S 5G',
        type: 'lcd',
        price: 13,
        stock: 100,
    },
    {
        name: 'SAMSUNG A02S 4G',
        type: 'lcd',
        price: 13,
        stock: 100,
    },
    {
        name: 'SAMSUNG A02 NF',
        type: 'lcd',
        price: 16,
        stock: 100,
    },
    {
        name: 'SAMSUNG A125 NF',
        type: 'lcd',
        price: 13,
        stock: 100,
    },
    {
        name: 'SAMSUNG A127 NF',
        type: 'lcd',
        price: 13,
        stock: 100,
    },
    {
        name: 'SAMSUNG A03 NF',
        type: 'lcd',
        price: 13,
        stock: 100,
    },
    {
        name: 'SAMSUNG A03S NF',
        type: 'lcd',
        price: 13,
        stock: 100,
    },
    {
        name: 'SAMSUNG A03 CORE',
        type: 'lcd',
        price: 13,
        stock: 100,
    },
    {
        name: 'SAMSUNG 13 4G NF',
        type: 'lcd',
        price: 16,
        stock: 100,
    },
    {
        name: 'SAMSUNG M336B NF',
        type: 'lcd',
        price: 16,
        stock: 100,
    },
    {
        name: 'SAMSUNG A11 NF',
        type: 'lcd',
        price: 17,
        stock: 100,
    },
    {
        name: 'SAMSUNG M13 NF',
        type: 'lcd',
        price: 15,
        stock: 100,
    },
    {
        name: 'SAMSUNG A10S NF',
        type: 'lcd',
        price: 13,
        stock: 100,
    },
    {
        name: 'SAMSUNG A10 NF',
        type: 'lcd',
        price: 13,
        stock: 100,
    },
    {
        name: 'SAMSUNG A20S NF',
        type: 'lcd',
        price: 14,
        stock: 100,
    },
    {
        name: 'SAMSUNG A20E NF',
        type: 'lcd',
        price: 15,
        stock: 100,
    },
    {
        name: 'SAMSUNG A21S NF',
        type: 'lcd',
        price: 17,
        stock: 100,
    },
    {
        name: 'SAMSUNG A22 5G NF',
        type: 'lcd',
        price: 15,
        stock: 100,
    },
    {
        name: 'SAMSUNG A32 5G NF',
        type: 'lcd',
        price: 15,
        stock: 100,
    },
    {
        name: 'SAMSUNG A23 4G NF',
        type: 'lcd',
        price: 15,
        stock: 100,
    },
    {
        name: 'SAMSUNG A23 5G NF',
        type: 'lcd',
        price: 18,
        stock: 100,
    },
    {
        name: 'SAMSUNG A 14 5GNF',
        type: 'lcd',
        price: 20,
        stock: 100,
    },
    {
        name: 'SAMSUNG A14 4G NF',
        type: 'lcd',
        price: 20,
        stock: 100,
    },
    {
        name: 'SAMSUNG J610 NF',
        type: 'lcd',
        price: 16,
        stock: 100,
    },
    {
        name: 'SAMSUNG A01 CORE NF',
        type: 'lcd',
        price: 15,
        stock: 100,
    },

    {
        name: 'SAMSUNG A10S',
        type: 'lcd',
        price: 30,
        stock: 100,
    },
    {
        name: 'SAMSUNG A22 4G',
        type: 'lcd',
        price: 40,
        stock: 100,
    },
    {
        name: 'SAMSUNG A32 4G',
        type: 'lcd',
        price: 50,
        stock: 100,
    },
    {
        name: 'SAMSUNG A30 4G',
        type: 'lcd',
        price: 50,
        stock: 100,
    },
    {
        name: 'SAMSUNG A31 4G',
        type: 'lcd',
        price: 50,
        stock: 100,
    },
    {
        name: 'SAMSUNG A30S',
        type: 'lcd',
        price: 45,
        stock: 100,
    },
    {
        name: 'SAMSUNG A33 4G GOLD',
        type: 'lcd',
        price: 60,
        stock: 100,
    },
    {
        name: 'SAMSUNG A33 BLACK',
        type: 'lcd',
        price: 62,
        stock: 100,
    },
    {
        name: 'SAMSUNG A34 BLACK',
        type: 'lcd',
        price: 62,
        stock: 100,
    },
    {
        name: 'SAMSUNG M31S',
        type: 'lcd',
        price: 65,
        stock: 100,
    },
    {
        name: 'SAMSUNG M31 4G',
        type: 'lcd',
        price: 55,
        stock: 100,
    },
    {
        name: 'SAMSUNG M21S/M30S',
        type: 'lcd',
        price: 50,
        stock: 100,
    },
    {
        name: 'SAMSUNG A20 4G',
        type: 'lcd',
        price: 45,
        stock: 100,
    },
    {
        name: 'SAMSUNG A40 4G',
        type: 'lcd',
        price: 60,
        stock: 100,
    },
    {
        name: 'SAMSUNG A41 4G',
        type: 'lcd',
        price: 60,
        stock: 100,
    },
    {
        name: 'SAMSUNG A42 4G',
        type: 'lcd',
        price: 40,
        stock: 100,
    },
    {
        name: 'SAMSUNG A50',
        type: 'lcd',
        price: 45,
        stock: 100,
    },
    {
        name: 'SAMSUNG A50S',
        type: 'lcd',
        price: 70,
        stock: 100,
    },
    {
        name: 'SAMSUNG A51 4G',
        type: 'lcd',
        price: 60,
        stock: 100,
    },
    {
        name: 'SAMSUNG A52 BLUE',
        type: 'lcd',
        price: 75,
        stock: 100,
    },
    {
        name: 'SAMSUNG A52 BLACK',
        type: 'lcd',
        price: 70,
        stock: 100,
    },
    {
        name: 'SAMSUNG A52S BLACK',
        type: 'lcd',
        price: 72,
        stock: 100,
    },
    {
        name: 'SAMSUNG A53 BLUE',
        type: 'lcd',
        price: 65,
        stock: 100,
    },
    {
        name: 'SAMSUNG A54 BLACK',
        type: 'lcd',
        price: 60,
        stock: 100,
    },
    {
        name: 'SAMSUNG A70 4G',
        type: 'lcd',
        price: 60,
        stock: 100,
    },
    {
        name: 'SAMSUNG A71 4G',
        type: 'lcd',
        price: 60,
        stock: 100,
    },
    {
        name: 'SAMSUNG A71 5G',
        type: 'lcd',
        price: 80,
        stock: 100,
    },
    {
        name: 'SAMSUNG A72 BLUE',
        type: 'lcd',
        price: 60,
        stock: 100,
    },
    {
        name: 'SAMSUNG A72 BACK',
        type: 'lcd',
        price: 65,
        stock: 100,
    },
    {
        name: 'SAMSUNG A80 BLACK',
        type: 'lcd',
        price: 70,
        stock: 100,
    },
    {
        name: 'SAMSUNG A80 GOOD',
        type: 'lcd',
        price: 65,
        stock: 100,
    },
    {
        name: 'SAMSUNG A920 BLACK',
        type: 'lcd',
        price: 60,
        stock: 100,
    },
    {
        name: 'SAMSUNG A520 BLACK',
        type: 'lcd',
        price: 50,
        stock: 100,
    },
    {
        name: 'SAMSUNG A520 GOLD',
        type: 'lcd',
        price: 45,
        stock: 100,
    },
    {
        name: 'SAMSUNG A750',
        type: 'lcd',
        price: 35,
        stock: 100,
    },
    {
        name: 'SAMSUNG A530 BLACK',
        type: 'lcd',
        price: 55,
        stock: 100,
    },
    {
        name: 'SAMSUNG A6+ BLACK',
        type: 'lcd',
        price: 58,
        stock: 100,
    },

    {
        name: 'SAMSUNG J330 BLACK',
        type: 'lcd',
        price: 22,
        stock: 100,
    },
    {
        name: 'SAMSUNG J320 GOLD',
        type: 'lcd',
        price: 22,
        stock: 100,
    },
    {
        name: 'SAMSUNG J500 BLACK',
        type: 'lcd',
        price: 22,
        stock: 100,
    },
    {
        name: 'SAMSUNG J530 BLACK',
        type: 'lcd',
        price: 45,
        stock: 100,
    },
    {
        name: 'SAMSUNG J530 GOLD',
        type: 'lcd',
        price: 45,
        stock: 100,
    },
    {
        name: 'SAMSUNG J730 GOLD',
        type: 'lcd',
        price: 50,
        stock: 100,
    },
    {
        name: 'SAMSUNG J730 BLACK',
        type: 'lcd',
        price: 50,
        stock: 100,
    },
    {
        name: 'SAMSUNG J700 BLACK',
        type: 'lcd',
        price: 35,
        stock: 100,
    },
    {
        name: 'SAMSUNG J600 BLACK',
        type: 'lcd',
        price: 45,
        stock: 100,
    },

    {
        name: 'SAMSUNG S6 NF',
        type: 'lcd',
        price: 55,
        stock: 100,
    },
    {
        name: 'SAMSUNG S6 EDGE BLACK',
        type: 'lcd',
        price: 55,
        stock: 100,
    },
    {
        name: 'SAMSUNG S6 EDGE GOLD',
        type: 'lcd',
        price: 50,
        stock: 100,
    },
    {
        name: 'SAMSUNG S7 EDGE BLACK',
        type: 'lcd',
        price: 95,
        stock: 100,
    },
    {
        name: 'SAMSUNG S7 EDGE SILVER',
        type: 'lcd',
        price: 95,
        stock: 100,
    },
    {
        name: 'SAMSUNG S7 NF',
        type: 'lcd',
        price: 55,
        stock: 100,
    },
    {
        name: 'SAMSUNG S8 BLUE',
        type: 'lcd',
        price: 90,
        stock: 100,
    },
    {
        name: 'SAMSUNG S8 BACK',
        type: 'lcd',
        price: 110,
        stock: 100,
    },
    {
        name: 'SAMSUNG S8 PLUS BLUE',
        type: 'lcd',
        price: 110,
        stock: 100,
    },
    {
        name: 'SAMSUNG S8 PLUS BLACK',
        type: 'lcd',
        price: 120,
        stock: 100,
    },
    {
        name: 'SAMSUNG S9 BLUE',
        type: 'lcd',
        price: 85,
        stock: 100,
    },
    {
        name: 'SAMSUNG S9 BLACK',
        type: 'lcd',
        price: 95,
        stock: 100,
    },
    {
        name: 'SAMSUNG S9 PLUS BLUE',
        type: 'lcd',
        price: 140,
        stock: 100,
    },
    {
        name: 'SAMSUNG S9 PLUS BLACK',
        type: 'lcd',
        price: 145,
        stock: 100,
    },
    {
        name: 'SAMSUNG S10 BLUE',
        type: 'lcd',
        price: 125,
        stock: 100,
    },
    {
        name: 'SAMSUNG S10 BLACK',
        type: 'lcd',
        price: 130,
        stock: 100,
    },
    {
        name: 'SAMSUNG S10 PLUS BLUE',
        type: 'lcd',
        price: 140,
        stock: 100,
    },
    {
        name: 'SAMSUNG S10E SILVER',
        type: 'lcd',
        price: 105,
        stock: 100,
    },
    {
        name: 'SAMSUNG S10 LITE BLACK',
        type: 'lcd',
        price: 110,
        stock: 100,
    },
    {
        name: 'SAMSUNG S20 BLUE',
        type: 'lcd',
        price: 150,
        stock: 100,
    },
    {
        name: 'SAMSUNG S20 PLUS GRAY',
        type: 'lcd',
        price: 150,
        stock: 100,
    },
    {
        name: 'SAMSUNG S20 FE BLUE',
        type: 'lcd',
        price: 75,
        stock: 100,
    },
    {
        name: 'SAMSUNG S21 FE BLUE',
        type: 'lcd',
        price: 95,
        stock: 100,
    },
    {
        name: 'SAMSUNG S21 5G GRAY',
        type: 'lcd',
        price: 120,
        stock: 100,
    },
    {
        name: 'SAMSUNG S21 PLUS BLUE',
        type: 'lcd',
        price: 122,
        stock: 100,
    },
    {
        name: 'SAMSUNG S21 ULTRA SILVER',
        type: 'lcd',
        price: 170,
        stock: 100,
    },
    {
        name: 'SAMSUNG S21 ULTRA BLACK',
        type: 'lcd',
        price: 175,
        stock: 100,
    },
    {
        name: 'SAMSUNG S20 ULTRA BLACK',
        type: 'lcd',
        price: 175,
        stock: 100,
    },
    {
        name: 'SAMSUNG S20 ULTRA GRAY',
        type: 'lcd',
        price: 165,
        stock: 100,
    },
    {
        name: 'SAMSUNG S22 ULTRA BURGUNDY',
        type: 'lcd',
        price: 225,
        stock: 100,
    },
    {
        name: 'SAMSUNG S22 ULTRA BLACK',
        type: 'lcd',
        price: 220,
        stock: 100,
    },
    {
        name: 'SAMSUNG S22 4G/5G BLACK',
        type: 'lcd',
        price: 115,
        stock: 100,
    },
    {
        name: 'SAMSUNG S22+ 5G BLACK',
        type: 'lcd',
        price: 120,
        stock: 100,
    },
    {
        name: 'SAMSUNG S23 BLACK',
        type: 'lcd',
        price: 115,
        stock: 100,
    },
    {
        name: 'SAMSUNG S23 PLUS',
        type: 'lcd',
        price: 150,
        stock: 100,
    },
    {
        name: 'SAMSUNG S23 ULTRA BLACK',
        type: 'lcd',
        price: 210,
        stock: 100,
    },

    {
        name: 'SAMSUNG NOTE 8 BLACK',
        type: 'lcd',
        price: 145,
        stock: 100,
    },
    {
        name: 'SAMSUNG NOTE 9 BLACK',
        type: 'lcd',
        price: 165,
        stock: 100,
    },
    {
        name: 'SAMSUNG NOTE 10',
        type: 'lcd',
        price: 165,
        stock: 100,
    },
    {
        name: 'SAMSUNG NOTE 10 LITE BLACK',
        type: 'lcd',
        price: 110,
        stock: 100,
    },
    {
        name: 'SAMSUNG NOTE 10 PLUS AURA',
        type: 'lcd',
        price: 200,
        stock: 100,
    },
    {
        name: 'SAMSUNG NOTE 20 GREEN',
        type: 'lcd',
        price: 130,
        stock: 100,
    },
    {
        name: 'SAMSUNG NOTE 20 ULTRA BLACK',
        type: 'lcd',
        price: 210,
        stock: 100,
    },
    {
        name: 'SAMSUNG NOTE 20 ULTRA BRONZE',
        type: 'lcd',
        price: 205,
        stock: 100,
    },
];
